version: '2.1'
orbs:
  slack: circleci/slack@4.1
jobs:
 
  plan-apply:
    working_directory: ~/project
    docker:
      - image: docker.mirror.hashicorp.services/hashicorp/terraform:light
    steps:
      - checkout
      - run:
          name: terraform init & plan
          command: |
            echo ssh key is ${SSH_BIG_APP}
            cd terraform
            terraform init -input=false
            terraform plan  
      - persist_to_workspace:
          root: .
          paths: 
            - .

  apply:
    docker:
      - image: docker.mirror.hashicorp.services/hashicorp/terraform:light
    steps:
      - attach_workspace:
          at: .
      - run:
          name: terraform
          command: |
            cd terraform
            terraform apply -auto-approve 
            terraform output -raw instance_pub_ip
      - run:
          name: github login
          command: |
            cd terraform
            scp -i pipe_ssh -o "StrictHostKeyChecking no" pipe_ssh ubuntu@184.73.136.88:/home/ubuntu
            ssh -i pipe_ssh -o "StrictHostKeyChecking no" ubuntu@184.73.136.88 'bash -s' << 'ENDSSH'
              cd /home/ubuntu
              chmod 400 pipe_ssh
              exec ssh-agent bash
              ssh-add pipe_ssh
              ssh -v hector6921@github.com &

            ENDSSH
      - run:
          name: dockerize
          command: |
            cd terraform
            ssh -i pipe_ssh -o "StrictHostKeyChecking no" ubuntu@184.73.136.88 'bash -s' << 'ENDSSH'

              # ssh -i pipe_ssh -o "StrictHostKeyChecking no" git@github.com
              git clone git@github.com:Kura-Team-6/pipe-in-a-pipe.git
              cd pipe-in-a-pipe
              git remote set-url origin git@github.com:Kura-Team-6/pipe-in-a-pipe.git
              cd pipe-in-a-pipe
              git checkout working
              cd client
              docker build -t react-container .
              cd ..
              cd backend-flask
              docker build -t flask-container .
              docker run -d react-container flask-container 

            ENDSSH 
 
      - persist_to_workspace:
          root: .
          paths:
            - .
  notify:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - slack/notify:
         event: fail
         template: basic_fail_1
      - slack/notify:
         event: pass
         template: success_tagged_deploy_1

  plan-destroy:
    docker:
      - image: docker.mirror.hashicorp.services/hashicorp/terraform:light
    steps:
      - attach_workspace:
          at: .
      - run:
          name: terraform create destroy plan
          command: |
            cd terraform
            terraform plan -destroy 
      - persist_to_workspace:
          root: .
          paths:
            - .

  destroy:
    docker:
      - image: docker.mirror.hashicorp.services/hashicorp/terraform:light
    steps:
      - attach_workspace:
          at: .
      - run:
          name: terraform destroy
          command: |
            cd terraform
            terraform apply -auto-approve 

workflows:
  version: 2
  plan_approve_apply:
    jobs:
      - plan-apply
      # - hold-apply:
      #     type: approval
      #     requires:
      #       - plan-apply
      - apply:
          requires:
            - plan-apply
#       - plan-destroy:
#           requires:
#             - apply
#       - hold-destroy:
#           type: approval
#           requires:
#             - plan-destroy
#       - destroy:
#           requires:
#             - hold-destroy

  send-notification:
    jobs:
      - notify:
          context: slack
