version: '2.1'
orbs:
  slack: circleci/slack@4.1
jobs:
  name: bad job
    - run:
        ssh -i efw.pem ubuntu@35.535.3.23
    
  notify:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - slack/notify:
         event: fail
         template: basic_fail_1
      - slack/notify:
         event: pass
         template: success_tagged_deploy_1

          
workflows:
  send-notification:
    jobs:
      - notify:
          context: slack
